### ISSUE TITLE
jeedoo fails if no match found?

### ISSUE THREAD

**Issue by wkearney99** [adultmm/AdultMediaManager#130]
Search for a movie where you know there's not going to be a match.  Repeatable using gibberish text like asdsdfsdfg 

Throws an error Message: The request was aborted: The connection was closed unexpectedly.

`
2024-10-13 10:01:11.6038,AdultScraper.Shared.ErrorReporter,AdultScraper.Shared.ErrorReporter+LoggerErrorReporter.ReportError,7,ERROR,An error occurred during searching for the movie.  Scraper: Jeedoo Message: The request was aborted: The connection was closed unexpectedly.,"EXCEPTION OCCURRED:System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at HtmlAgilityPack.HtmlWeb.Get(Uri uri, String method, String path, HtmlDocument doc, IWebProxy proxy, ICredentials creds)
   at HtmlAgilityPack.HtmlWeb.LoadUrl(Uri uri, String method, WebProxy proxy, NetworkCredential creds)
   at HtmlAgilityPack.HtmlWeb.Load(Uri uri, String method)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at AdultScraper.Shared.JeedooScraper.SearchOnSiteByTitle(String title, Nullable`1 year, String lang, String moviePath, SearchResultContainer`1 results, Int32 page)
   at AdultScraper.Shared.JeedooScraper.SearchByTitle(String title, Nullable`1 year, String lang, String moviePath, SearchResultContainer`1 results)
   at AdultScraper.Shared.MovieScraper.SearchByTitle(String title, Nullable`1 year, String lang, String moviePath)*   at System.Net.HttpWebRequest.GetResponse()
   at HtmlAgilityPack.HtmlWeb.Get(Uri uri, String method, String path, HtmlDocument doc, IWebProxy proxy, ICredentials creds)
   at HtmlAgilityPack.HtmlWeb.LoadUrl(Uri uri, String method, WebProxy proxy, NetworkCredential creds)
   at HtmlAgilityPack.HtmlWeb.Load(Uri uri, String method)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at AdultScraper.Shared.JeedooScraper.SearchOnSiteByTitle(String title, Nullable`1 year, String lang, String moviePath, SearchResultContainer`1 results, Int32 page)
   at AdultScraper.Shared.JeedooScraper.SearchByTitle(String title, Nullable`1 year, String lang, String moviePath, SearchResultContainer`1 results)
   at AdultScraper.Shared.MovieScraper.SearchByTitle(String title, Nullable`1 year, String lang, String moviePath)"
`

**Comment by adultmm** [comment]
Fixed in [v1.0.1](https://github.com/adultmm/AdultMediaManager/releases/tag/v1.0.1).
